import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import type { AppProps } from "next/app";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import { TerminalContextProvider } from "react-terminal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
 * Component is the active page
 * UserProvider is a wrapper that allows us to access auth0 features globally throughout the app
 */
export default function MyApp({ Component, pageProps }: AppProps) {
  // React-query
  const queryClient = new QueryClient();

  return (
    <UserProvider>
      <QueryClientProvider client={queryClient}>
        <TerminalContextProvider>
          <Component {...pageProps} />
        </TerminalContextProvider>
      </QueryClientProvider>
    </UserProvider>
  );
}
