# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node Server CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: ./src/leo-server-app/package-lock.json

      - name: Clean Install Server App
        run: npm ci
        working-directory: ./src/leo-server-app
      - name: Build Server App
        run: npm run build --if-present
        working-directory: ./src/leo-server-app
      - name: Test Server App
        env:
          SPACE_TRACK_USERNAME: ${{ secrets.SPACE_TRACK_USERNAME }}
          SPACE_TRACK_PASSWORD: ${{ secrets.SPACE_TRACK_PASSWORD }}
        run: npm run test
        working-directory: ./src/leo-server-app
